/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.4.0.0                                               */
/*  Date (dd.mm.yyyy): 30.12.2025   Time (hh:mm): 11:47                        */
/*******************************************************************************/


#ifndef _GFORCEGUI_DISPLAY_1_RESOURCES_H_
#define _GFORCEGUI_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

#if !defined(GX_UTF8_SUPPORT)
#error "The symbol GX_UTF8_SUPPORT must be defined to support the Studio project settings".
#endif

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 256
#define DISPLAY_1_Y_RESOLUTION 320
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_G_HIGH 29
#define GX_COLOR_ID_G_MEDIUM 30
#define GX_COLOR_ID_G_NORMAL 31
#define GX_COLOR_ID_G_LOW 32
#define DISPLAY_1_COLOR_TABLE_SIZE 33

/* Font ID definitions                                                         */

#define GX_FONT_ID_VALUE_TOTAL 4
#define GX_FONT_ID_TITLE 5
#define GX_FONT_ID_SUBTITLE 6
#define GX_FONT_ID_VALUE_AXIS 7
#define GX_FONT_ID_INSTRUCTIONS 8
#define DISPLAY_1_FONT_TABLE_SIZE 9

/* Pixelmap ID definitions                                                     */

#define DISPLAY_1_PIXELMAP_TABLE_SIZE 5

/* String Ids                                                                  */

#define GX_STRING_ID_TITLE 1
#define GX_STRING_ID_SUBTITLE 2
#define GX_STRING_ID_INSTRUCTIONS 3
#define DISPLAY_1_STRING_TABLE_SIZE 4

#endif                                       /* sentry                         */
